# Generated by Django 5.2.8 on 2025-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_medecine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedecine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
